import React from 'react';
import styles from './VideoEmbed.module.css';

interface VideoEmbedProps {
  title: string;
  description?: string;
  videoId: string; // YouTube video ID
  duration?: string;
  topics?: string[];
  height?: string;
}

/**
 * VideoEmbed Component
 * Embeds YouTube videos with metadata and transcript support
 */
export default function VideoEmbed({
  title,
  description,
  videoId,
  duration = '10:00',
  topics = [],
  height = '400px',
}: VideoEmbedProps): JSX.Element {
  const [showTranscript, setShowTranscript] = React.useState(false);

  return (
    <div className={styles.videoContainer}>
      <div className={styles.header}>
        <div className={styles.titleSection}>
          <h4 className={styles.title}>🎥 {title}</h4>
          <span className={styles.duration}>⏱️ {duration}</span>
        </div>
      </div>

      {description && <p className={styles.description}>{description}</p>}

      <div className={styles.videoWrapper} style={{ aspectRatio: '16 / 9' }}>
        <iframe
          className={styles.iframe}
          src={`https://www.youtube.com/embed/${videoId}?rel=0`}
          title={title}
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
          allowFullScreen
        />
      </div>

      {topics.length > 0 && (
        <div className={styles.topics}>
          <span className={styles.topicsLabel}>📚 Topics covered:</span>
          <div className={styles.topicsList}>
            {topics.map((topic, idx) => (
              <span key={idx} className={styles.topic}>
                {topic}
              </span>
            ))}
          </div>
        </div>
      )}

      <div className={styles.actions}>
        <a
          href={`https://www.youtube.com/watch?v=${videoId}`}
          target="_blank"
          rel="noopener noreferrer"
          className={styles.actionBtn}
        >
          📺 Watch on YouTube
        </a>
        <button
          className={styles.actionBtn}
          onClick={() => setShowTranscript(!showTranscript)}
        >
          {showTranscript ? '▼ Hide Transcript' : '▶ Show Transcript'}
        </button>
      </div>

      {showTranscript && (
        <div className={styles.transcript}>
          <p className={styles.transcriptNotice}>
            💡 <strong>Note:</strong> Transcript will be available for videos uploaded
            with captions. YouTube automatically generates transcripts for most videos.
          </p>
          <p className={styles.transcriptText}>
            [Transcript auto-generated by YouTube - click "Watch on YouTube" → select CC
            button → choose transcript]
          </p>
        </div>
      )}
    </div>
  );
}
